In [2]:
!pip install joblib 

In [24]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import os
import joblib
style.use("ggplot")
# Set the seed value for the notebook so the results are reproducible
from numpy.random import seed
seed(1)

# from matplotlib import rcParams
# rcParams['figure.figsize'] = 10, 8

In [4]:

# linear regression feature importance
from sklearn.datasets import make_regression
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import sklearn
import sklearn.datasets

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


# Read the CSV and Perform Basic Data Cleaning

In [5]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head(100)

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0        CONFIRMED              0              0              0   
1   FALSE POSITIVE              0              1              0   
2   FALSE POSITIVE              0              1              0   
3        CONFIRMED              0              0              0   
4        CONFIRMED              0              0              0   
..             ...            ...            ...            ...   
95       CONFIRMED              0              0              0   
96       CONFIRMED              0              0              0   
97       CONFIRMED              0              0              0   
98       CONFIRMED              0              0              0   
99       CONFIRMED              0              0              0   

    koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0               0   54.418383     2.479000e-04    -2.479000e-04   162.513840   
1               0   19.899140     1.490000e-05    -1.490000e-05   175.850252   
2               0    1.736952     2.630000e-07    -2.630000e-07   170.307565   
3               0    2.525592     3.760000e-06    -3.760000e-06   171.595550   
4               0    4.134435     1.050000e-05    -1.050000e-05   172.979370   
..            ...         ...              ...              ...          ...   
95              0    8.103633     2.030000e-05    -2.030000e-05   176.948600   
96              0    4.715108     1.940000e-05    -1.940000e-05   134.961780   
97              0    6.365840     8.060000e-06    -8.060000e-06   171.135750   
98              0    3.040330     3.370000e-07    -3.370000e-07   169.949011   
99              0   31.330461     3.980000e-05    -3.980000e-05   153.430310   

    koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0           0.003520  ...             -81      4.467           0.064   
1           0.000581  ...            -176      4.544           0.044   
2           0.000115  ...            -174      4.564           0.053   
3           0.001130  ...            -211      4.438           0.070   
4           0.001900  ...            -232      4.486           0.054   
..               ...  ...             ...        ...             ...   
95          0.002050  ...            -146      4.574           0.054   
96          0.003240  ...            -146      4.574           0.054   
97          0.001000  ...            -155      4.554           0.042   
98          0.000089  ...            -151      4.519           0.084   
99          0.001030  ...            -105      4.581           0.010   

    koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0           -0.096     0.927          0.105         -0.061  291.93423   
1           -0.176     0.868          0.233         -0.078  297.00482   
2           -0.168     0.791          0.201         -0.067  285.53461   
3           -0.210     1.046          0.334         -0.133  288.75488   
4           -0.229     0.972          0.315         -0.105  296.28613   
..             ...       ...            ...            ...        ...   
95          -0.041     0.732          0.062         -0.068  283.22141   
96          -0.041     0.732          0.062         -0.068  283.22141   
97          -0.168     0.849          0.212         -0.071  291.14951   
98          -0.063     0.791          0.071         -0.087  299.31610   
99          -0.085     0.817          0.080         -0.029  292.23676   

          dec  koi_kepmag  
0   48.141651      15.347  
1   48.134129      15.436  
2   48.285210      15.597  
3   48.226200      15.509  
4   48.224670      15.714  
..        ...         ...  
95  40.421829      15.289  
96  40.421829      15.289  
97  40.420521      15.090  
98  40.822380      15.028  
99  41.085880      15.855  

[100 rows x 41 columns]

In [6]:
df_drop_disposition=df.drop(['koi_disposition'], axis=1)
df_drop_disposition

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0                 0              0              0              0   54.418383   
1                 0              1              0              0   19.899140   
2                 0              1              0              0    1.736952   
3                 0              0              0              0    2.525592   
4                 0              0              0              0    4.134435   
...             ...            ...            ...            ...         ...   
6986              0              0              0              1    8.589871   
6987              0              1              1              0    0.527699   
6988              0              0              0              0    1.739849   
6989              0              0              1              0    0.681402   
6990              0              0              1              1    4.856035   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
0        2.479000e-04    -2.479000e-04   162.513840          0.003520   
1        1.490000e-05    -1.490000e-05   175.850252          0.000581   
2        2.630000e-07    -2.630000e-07   170.307565          0.000115   
3        3.760000e-06    -3.760000e-06   171.595550          0.001130   
4        1.050000e-05    -1.050000e-05   172.979370          0.001900   
...               ...              ...          ...               ...   
6986     1.846000e-04    -1.846000e-04   132.016100          0.015700   
6987     1.160000e-07    -1.160000e-07   131.705093          0.000170   
6988     1.780000e-05    -1.780000e-05   133.001270          0.007690   
6989     2.430000e-06    -2.430000e-06   132.181750          0.002850   
6990     6.360000e-05    -6.360000e-05   135.993300          0.010800   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0            -0.003520  ...             -81      4.467           0.064   
1            -0.000581  ...            -176      4.544           0.044   
2            -0.000115  ...            -174      4.564           0.053   
3            -0.001130  ...            -211      4.438           0.070   
4            -0.001900  ...            -232      4.486           0.054   
...                ...  ...             ...        ...             ...   
6986         -0.015700  ...            -152      4.296           0.231   
6987         -0.000170  ...            -166      4.529           0.035   
6988         -0.007690  ...            -220      4.444           0.056   
6989         -0.002850  ...            -236      4.447           0.056   
6990         -0.010800  ...            -225      4.385           0.054   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0             -0.096     0.927          0.105         -0.061  291.93423   
1             -0.176     0.868          0.233         -0.078  297.00482   
2             -0.168     0.791          0.201         -0.067  285.53461   
3             -0.210     1.046          0.334         -0.133  288.75488   
4             -0.229     0.972          0.315         -0.105  296.28613   
...              ...       ...            ...            ...        ...   
6986          -0.189     1.088          0.313         -0.228  298.74921   
6987          -0.196     0.903          0.237         -0.079  297.18875   
6988          -0.224     1.031          0.341         -0.114  286.50937   
6989          -0.224     1.041          0.341         -0.114  294.16489   
6990          -0.216     1.193          0.410         -0.137  297.00977   

            dec  koi_kepmag  
0     48.141651      15.347  
1     48.134129      15.436  
2     48.285210      15.597  
3     48.226200      15.509  
4     48.224670      15.714  
...         ...         ...  
6986  46.973351      14.478  
6987  47.093819      14.082  
6988  47.163219      14.757  
6989  47.176281      15.385  
6990  47.121021      14.826  

[6991 rows x 40 c

In [7]:
koi_disposition=df['koi_disposition']

data = koi_disposition.copy()


# Select your features (columns)

In [8]:
# define dataset

X = df_drop_disposition
y= koi_disposition



# Create a Train Test Split

Use `koi_disposition` for the y values

In [10]:
#create train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)


label_encoder=LabelEncoder()
label_encoder.fit(y_train)
y_train_encoded=label_encoder.transform(y_train)
y_test_encoded=label_encoder.transform(y_test)

y_train_categorical=to_categorical(y_train_encoded)
y_test_categorical=to_categorical(y_test_encoded)

print(y_test_categorical)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [11]:
X_train.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
6122              0              0              0              0    6.768901   
6370              0              1              0              1    0.733726   
2879              1              0              0              0    7.652707   
107               0              0              0              0    7.953547   
29                0              0              0              0    4.959319   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
6122     7.380000e-05    -7.380000e-05   133.077240          0.008440   
6370     6.060000e-06    -6.060000e-06   132.020050          0.007950   
2879     6.540000e-05    -6.540000e-05   134.460380          0.006190   
107      1.910000e-05    -1.910000e-05   174.662240          0.001820   
29       5.150000e-07    -5.150000e-07   172.258529          0.000083   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
6122         -0.008440  ...            -171      4.327           0.153   
6370         -0.007950  ...            -175      4.578           0.033   
2879         -0.006190  ...            -189      4.481           0.050   
107          -0.001820  ...             -85      4.536           0.056   
29           -0.000083  ...             -77      4.359           0.110   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
6122          -0.187     1.125          0.310         -0.207  294.40472   
6370          -0.187     0.797          0.211         -0.056  284.50391   
2879          -0.200     0.963          0.290         -0.097  295.50211   
107           -0.016     0.779          0.023         -0.049  291.15878   
29            -0.110     1.082          0.173         -0.130  292.16705   

            dec  koi_kepmag  
6122  39.351681      14.725  
6370  42.463860      15.770  
2879  38.983540      13.099  
107   40.750271      15.660  
29    48.727589      15.263  

[5 rows x 40 columns]

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [12]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import Dense

# Create a StandardScater model and fit it to the training data
X_scaler = StandardScaler().fit(X_train)

# Scale your data
X_train_scaled=X_scaler.transform(X_train)
X_test_scaled=X_scaler.transform(X_test)

from tensorflow import keras
from tensorflow.keras import layers

# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(50, activation="relu", name="layer1", input_dim=40),
        layers.Dense(25, activation="relu", name="layer2" ),
        layers.Dense(3, activation= "softmax", name="layer3"),
    ]
)


model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer1 (Dense)               (None, 50)                2050      
_________________________________________________________________
layer2 (Dense)               (None, 25)                1275      
_________________________________________________________________
layer3 (Dense)               (None, 3)                 78        
Total params: 3,403
Trainable params: 3,403
Non-trainable params: 0
_________________________________________________________________


In [13]:
opt = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [14]:
print(len(X_train_scaled))
print(len(y_train_categorical))

5243
5243


In [15]:
# # fit the model
# model.fit(X_train_scaled, y_train_categorical)
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
164/164 - 0s - loss: 0.4259 - accuracy: 0.8253
Epoch 2/100
164/164 - 0s - loss: 0.2973 - accuracy: 0.8739
Epoch 3/100
164/164 - 0s - loss: 0.2644 - accuracy: 0.8894
Epoch 4/100
164/164 - 0s - loss: 0.2789 - accuracy: 0.8837
Epoch 5/100
164/164 - 0s - loss: 0.2494 - accuracy: 0.8928
Epoch 6/100
164/164 - 0s - loss: 0.2470 - accuracy: 0.8945
Epoch 7/100
164/164 - 0s - loss: 0.2398 - accuracy: 0.8991
Epoch 8/100
164/164 - 0s - loss: 0.2361 - accuracy: 0.8993
Epoch 9/100
164/164 - 0s - loss: 0.2230 - accuracy: 0.9035
Epoch 10/100
164/164 - 0s - loss: 0.2307 - accuracy: 0.9025
Epoch 11/100
164/164 - 0s - loss: 0.2189 - accuracy: 0.9048
Epoch 12/100
164/164 - 0s - loss: 0.2177 - accuracy: 0.9071
Epoch 13/100
164/164 - 0s - loss: 0.2344 - accuracy: 0.9035
Epoch 14/100
164/164 - 0s - loss: 0.2229 - accuracy: 0.9090
Epoch 15/100
164/164 - 0s - loss: 0.2157 - accuracy: 0.9065
Epoch 16/100
164/164 - 0s - loss: 0.2065 - accuracy: 0.9125
Epoch 17/100
164/164 - 0s - loss: 0.2202 - accura

In [16]:
#test the model
model.evaluate(X_test_scaled, y_test_categorical)

55/55 [==============================] - 0s 592us/step - loss: 0.7628 - accuracy: 0.8764


[0.7628031373023987, 0.8764302134513855]

# Train the Model



In [17]:
print(f"Training Data Score: {model.evaluate(X_train_scaled, y_train_categorical)}")
print(f"Testing Data Score: {model.evaluate(X_test_scaled, y_test_categorical)}")

164/164 [==============================] - 0s 556us/step - loss: 0.0914 - accuracy: 0.9601
Training Data Score: [0.09144587814807892, 0.9601373076438904]
55/55 [==============================] - 0s 683us/step - loss: 0.7628 - accuracy: 0.8764
Testing Data Score: [0.7628031373023987, 0.8764302134513855]


# Save the Model

In [25]:

filename = 'jmh_keras.sav'

model.save("models")

INFO:tensorflow:Assets written to: models\assets


In [19]:

model_loaded = keras.models.load_model("models")

In [20]:
model_loaded.evaluate(X_test_scaled, y_test_categorical)

55/55 [==============================] - 0s 665us/step - loss: 0.7628 - accuracy: 0.8764


[0.7628031373023987, 0.8764302134513855]

In [26]:
new_data = (X_test_scaled)


print(f"Predicted class: {model.predict_classes(new_data)}")

#Where am I assigning which number (0,1,2) corresponds to which status (Confirmed, False Positive, Candidate)

Predicted class: [2 0 2 ... 1 0 0]


C:\Users\hanso\Anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [32]:
# counts = df.nunique()
# counts

print(df['koi_disposition'].value_counts())

FALSE POSITIVE    3504
CONFIRMED         1800
CANDIDATE         1687
Name: koi_disposition, dtype: int64


In [41]:
print(y_test.value_counts())

FALSE POSITIVE    853
CONFIRMED         484
CANDIDATE         411
Name: koi_disposition, dtype: int64


In [40]:
predicted_class=model.predict_classes(new_data)

predicted_class_df=pd.DataFrame(predicted_class)

print(predicted_class_df.value_counts())

2    858
1    503
0    387
dtype: int64


In [ ]:
# 2's are False Positives
# 1's are Confirmed
# 0's are Candidates